{application,secure_chat,
             [{description,"Secure Messaging Backend"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{secure_chat_app,[]}},
              {applications,[kernel,stdlib,cowboy,jsx,epgsql,jose]},
              {env,[]},
              {modules,[auth_handler,db_manager,secure_chat_app,
                        secure_chat_sup,ws_handler]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
